### ISSUE TITLE
About app name

### ISSUE THREAD

**Issue by A6GibKm** [UnicornyRainbow/Secrets#1]
Hello, I am one of the maintainers of a similarly named app [Secrets](https://gitlab.gnome.org/World/secrets). I think it would be in the best interest of both projects to have distinctive and unique branding, given the similar domains of the apps.

For reference, our app was renamed to Secrets on Aug 24 2021.

**Comment by UnicornyRainbow** [comment]
Hey, at the point I originally named my app Secrets I wasn't aware of your project, however I fully agree with you.
I would be willing to rename my App, once I can come up with a proper name.

If you have any suggestions, I would be happy to consider them.

**Comment by bragefuglseth** [comment]
Maybe Key Cutter could work? The name follows GNOME’s guidelines, and is a good physical metaphor for what the app does.

**Comment by UnicornyRainbow** [comment]
I think I like that name
I changed the displayed name in 52af0cd1e0e7db22fc5b42732fa8ef792dd3a6aa
I will change the app id at a later point, that will take some time to prepare everything

**Comment by A6GibKm** [comment]
Changing the app id is not necessary and might create problems. While I do not oppose to it, there isn't a big benefit to it.

**Comment by UnicornyRainbow** [comment]
The changes are live on Flathub, going to close this issue
