### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Vistaus** [UnicornyRainbow/Secrets#3]
It would be great if you could make the app translatable. If you do, I will provide the Dutch translation. 🙂

**Comment by UnicornyRainbow** [comment]
Ohhh, cool to hear that you are interested in a translation!
But to be honest, I have no idea how that works with Gtk... let me look into that and update this issue as sonnas I figured it out
Thank you for your help!

**Comment by UnicornyRainbow** [comment]
Also I could provide a german translation

**Comment by UnicornyRainbow** [comment]
I restructured the app entirely to follow the gnome builder template, you should be able to clone it and build with builder without any additional effort.
Builder generates a po directory, however I cannot find out, how to generate the actual .po files...

**Comment by UnicornyRainbow** [comment]
hi, sorry it took over a year... anyway, I got around to it and added translation support^^, see the README and `src/po` for more info

**Comment by Vistaus** [comment]
No problem! Thanks for adding it anyway. 🙂 I'll start working on it ASAP.

**Comment by UnicornyRainbow** [comment]
nice, thanks! just open another issue if you encounter any problems and i'll try to help you / fix them
