### ISSUE TITLE
Increase window size on load and save special characters list

### ISSUE THREAD

**Issue by lexo-mfleuti** [UnicornyRainbow/Secrets#4]
The tools is almost perfect. The only thing I really miss is that it remembers the special characters list. Also if the window size would be a bit bigger and the special characters list to be unfolded by default that's be great. 

Basically the tool should remember all settings made upon closing.

Thanks for this very simple yet nice and practical tool.

**Comment by UnicornyRainbow** [comment]
Heyy, thanks for the suggestions. I wanted to provide secure and compatible default and didn't want to bother remembering changes and especially being able to reset the changes. But I guess it remembering the special characters and and if they are expanded or not should not be to hard to implement. If I find some time I will implement them (or if you want you can implement them yourself and open a pull request). I'm not shure about remembering the window size, I want to maintain a relatively adaptive layout that is compatible with many screen sizes and I'm not sure how well GTK gets along with a custom set window size... let's see, if it is possible without sacrificing responsiveness I think I can implement that as well.

**Comment by UnicornyRainbow** [comment]
Hey @lexo-mfleuti I implemented your request in 86b68d8020d6ea47ef7dce94b4a352fd279f1fd8
I opened flathub/io.github.unicornyrainbow.secrets#4, it will generate a test build, you can use it to test if you want, otherwise it will be live the next days

**Comment by UnicornyRainbow** [comment]
soooo... apparently changed a lot of stuff they view as mandatory metadata in the last year...
anyway, you can test it with this command:
```bash
flatpak install --user https://dl.flathub.org/build-repo/110538/io.github.unicornyrainbow.secrets.flatpakref
```
otherwise there should be an official update soon

**Comment by lexo-mfleuti** [comment]
Thank you very much @UnicornyRainbow for the changes - now it's perfect! Thanks again for this very simple yet extremely practical tool! Sorry for not answering. I'm not on Github very often and I did not notice any messages. If you [set-up sponsoring](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account) or have Monero Wallet Address I can donate something.
